from PyQt6 import QtCore, QtGui, QtWidgets

from outBatch import Ui_BatchUpdate
from outPayment import Ui_completePay
from datamanage import addEntry


class Ui_MainWindow(object):
    def updateBatch(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_BatchUpdate()
        self.ui.setupUi(self.window)
        self.window.show()

    def completePay(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_completePay()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(251, 271)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(20, 20, 49, 16))
        self.nameLabel.setObjectName("nameLabel")
        self.ageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel.setGeometry(QtCore.QRect(20, 60, 49, 16))
        self.ageLabel.setObjectName("ageLabel")
        self.batchLabel = QtWidgets.QLabel(self.centralwidget)
        self.batchLabel.setGeometry(QtCore.QRect(20, 140, 49, 16))
        self.batchLabel.setObjectName("batchLabel")
        self.addLabel = QtWidgets.QLabel(self.centralwidget)
        self.addLabel.setGeometry(QtCore.QRect(20, 100, 49, 16))
        self.addLabel.setObjectName("addLabel")
        self.nameText = QtWidgets.QLineEdit(self.centralwidget)
        self.nameText.setGeometry(QtCore.QRect(70, 20, 161, 21))
        self.nameText.setObjectName("nameText")
        self.payBtn = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.addEntry())
        self.payBtn.setGeometry(QtCore.QRect(70, 190, 101, 24))
        self.payBtn.setObjectName("payBtn")
        self.addText = QtWidgets.QLineEdit(self.centralwidget)
        self.addText.setGeometry(QtCore.QRect(70, 100, 161, 21))
        self.addText.setObjectName("addText")
        self.ageSelect = QtWidgets.QComboBox(self.centralwidget)
        self.ageSelect.setGeometry(QtCore.QRect(70, 60, 68, 22))
        self.ageSelect.setObjectName("ageSelect")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.ageSelect.addItem("")
        self.batchSelect = QtWidgets.QComboBox(self.centralwidget)
        self.batchSelect.setGeometry(QtCore.QRect(70, 140, 68, 22))
        self.batchSelect.setObjectName("batchSelect")
        self.batchSelect.addItem("")
        self.batchSelect.addItem("")
        self.batchSelect.addItem("")
        self.batchSelect.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 251, 22))
        self.menubar.setObjectName("menubar")
        self.menuUpdate_Batch = QtWidgets.QMenu(self.menubar)
        self.menuUpdate_Batch.setObjectName("menuUpdate_Batch")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionComplete_Payment = QtGui.QAction(MainWindow)
        self.actionComplete_Payment.setObjectName("actionComplete_Payment")
        self.actionComplete_Payment.triggered.connect(lambda: self.completePay())

        self.actionUpdate_Batch = QtGui.QAction(MainWindow)
        self.actionUpdate_Batch.setObjectName("actionUpdate_Batch")
        self.actionUpdate_Batch.triggered.connect(lambda: self.updateBatch())

        self.menuUpdate_Batch.addAction(self.actionComplete_Payment)
        self.menuUpdate_Batch.addAction(self.actionUpdate_Batch)
        self.menubar.addAction(self.menuUpdate_Batch.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def resetTextBox(self):
        self.nameText.setText("")
        self.addText.setText("")

    def addEntry(self):
        name = self.nameText.text()
        address = self.addText.text()
        batch = self.batchSelect.currentText()
        age = self.ageSelect.currentText()
        regNo = False
        
        if not name:
            dlg = CustomDialog("Error", "Enter Name")
            dlg.exec()
        elif not address:
            dlg = CustomDialog("Error", "Enter Address")
            dlg.exec()
        else:
            regNo = addEntry(name, address, age, batch)
        
        if regNo != False:
            dlg = CustomDialog("Success", "Proceed to Payment", "Your reg no is: " + str(regNo) + '\n')
            dlg.exec()
            self.resetTextBox()
        elif regNo == False:
            dlg = CustomDialog("Error", "Entry already exists")
            dlg.exec()
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Yoga"))
        self.nameLabel.setText(_translate("MainWindow", "Name :"))
        self.ageLabel.setText(_translate("MainWindow", "Age:"))
        self.batchLabel.setText(_translate("MainWindow", "Batch:"))
        self.addLabel.setText(_translate("MainWindow", "Address:"))
        self.payBtn.setText(_translate("MainWindow", "Confirm"))
        self.ageSelect.setItemText(0, _translate("MainWindow", "18"))
        self.ageSelect.setItemText(1, _translate("MainWindow", "19"))
        self.ageSelect.setItemText(2, _translate("MainWindow", "20"))
        self.ageSelect.setItemText(3, _translate("MainWindow", "21"))
        self.ageSelect.setItemText(4, _translate("MainWindow", "22"))
        self.ageSelect.setItemText(5, _translate("MainWindow", "23"))
        self.ageSelect.setItemText(6, _translate("MainWindow", "24"))
        self.ageSelect.setItemText(7, _translate("MainWindow", "25"))
        self.ageSelect.setItemText(8, _translate("MainWindow", "26"))
        self.ageSelect.setItemText(9, _translate("MainWindow", "27"))
        self.ageSelect.setItemText(10, _translate("MainWindow", "28"))
        self.ageSelect.setItemText(11, _translate("MainWindow", "29"))
        self.ageSelect.setItemText(12, _translate("MainWindow", "30"))
        self.ageSelect.setItemText(13, _translate("MainWindow", "31"))
        self.ageSelect.setItemText(14, _translate("MainWindow", "32"))
        self.ageSelect.setItemText(15, _translate("MainWindow", "33"))
        self.ageSelect.setItemText(16, _translate("MainWindow", "34"))
        self.ageSelect.setItemText(17, _translate("MainWindow", "35"))
        self.ageSelect.setItemText(18, _translate("MainWindow", "36"))
        self.ageSelect.setItemText(19, _translate("MainWindow", "37"))
        self.ageSelect.setItemText(20, _translate("MainWindow", "38"))
        self.ageSelect.setItemText(21, _translate("MainWindow", "39"))
        self.ageSelect.setItemText(22, _translate("MainWindow", "40"))
        self.ageSelect.setItemText(23, _translate("MainWindow", "41"))
        self.ageSelect.setItemText(24, _translate("MainWindow", "42"))
        self.ageSelect.setItemText(25, _translate("MainWindow", "43"))
        self.ageSelect.setItemText(26, _translate("MainWindow", "44"))
        self.ageSelect.setItemText(27, _translate("MainWindow", "45"))
        self.ageSelect.setItemText(28, _translate("MainWindow", "46"))
        self.ageSelect.setItemText(29, _translate("MainWindow", "47"))
        self.ageSelect.setItemText(30, _translate("MainWindow", "48"))
        self.ageSelect.setItemText(31, _translate("MainWindow", "49"))
        self.ageSelect.setItemText(32, _translate("MainWindow", "50"))
        self.ageSelect.setItemText(33, _translate("MainWindow", "51"))
        self.ageSelect.setItemText(34, _translate("MainWindow", "52"))
        self.ageSelect.setItemText(35, _translate("MainWindow", "53"))
        self.ageSelect.setItemText(36, _translate("MainWindow", "54"))
        self.ageSelect.setItemText(37, _translate("MainWindow", "55"))
        self.ageSelect.setItemText(38, _translate("MainWindow", "56"))
        self.ageSelect.setItemText(39, _translate("MainWindow", "57"))
        self.ageSelect.setItemText(40, _translate("MainWindow", "58"))
        self.ageSelect.setItemText(41, _translate("MainWindow", "59"))
        self.ageSelect.setItemText(42, _translate("MainWindow", "60"))
        self.ageSelect.setItemText(43, _translate("MainWindow", "61"))
        self.ageSelect.setItemText(44, _translate("MainWindow", "62"))
        self.ageSelect.setItemText(45, _translate("MainWindow", "63"))
        self.ageSelect.setItemText(46, _translate("MainWindow", "64"))
        self.ageSelect.setItemText(47, _translate("MainWindow", "65"))
        self.batchSelect.setItemText(0, _translate("MainWindow", "6-7AM"))
        self.batchSelect.setItemText(1, _translate("MainWindow", "7-8AM"))
        self.batchSelect.setItemText(2, _translate("MainWindow", "8-9AM"))
        self.batchSelect.setItemText(3, _translate("MainWindow", "5-6PM"))
        self.menuUpdate_Batch.setTitle(_translate("MainWindow", "Options"))
        self.actionComplete_Payment.setText(_translate("MainWindow", "Complete Payment"))
        self.actionUpdate_Batch.setText(_translate("MainWindow", "Update Batch"))

class CustomDialog(QtWidgets.QDialog):
    def __init__(self, title, s, regNo = ''):
        super().__init__()

        self.setWindowTitle(title)

        QBtn = QtWidgets.QDialogButtonBox.StandardButton.Ok

        self.buttonBox = QtWidgets.QDialogButtonBox(QBtn)
        self.buttonBox.accepted.connect(self.accept)
        

        self.layout = QtWidgets.QVBoxLayout()
        message = QtWidgets.QLabel(regNo + s)
        self.layout.addWidget(message)
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
